language: go

go:
    - 1.15.x

script:
    - go test -v ./werewolves
    - go build ./cmd/server

after_success:
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash <(curl -s https://codecov.io/bash); fi
