services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
  server:
    container_name: werewolves-backend
    build: ./
    restart: always
    ports:
      - 7070:7070
    env_file:
      - .env
  migrate:
    build: ./storage/migrate/
    env_file:
      - .env
volumes:
  data:

